const propertyState = {
  booleanValue: 0,
  binaryValue: 1,
  eventType: 2,
  polarity: 3,
  programChange: 4,
  programState: 5,
  reasonForHalt: 6,
  reliability: 7,
  eventState: 8,
  systemStatus: 9,
  units: 10,
  unsignedValue: 11,
  lifeSafetyMode: 12,
  lifeSafetyState: 13,
  restartReason: 14,
  doorAlarmState: 15,
  action: 16,
  doorSecuredStatus: 17,
  doorStatus: 18,
  doorValue: 19,
  fileAccessMethod: 20,
  lockStatus: 21,
  lifeSafetyOperation: 22,
  maintenance: 23,
  nodeType: 24,
  notifyType: 25,
  securityLevel: 26,
  shedState: 27,
  silencedState: 28,
  accessEvent: 30,
  zoneOccupancyState: 31,
  accessCredDisableReason: 32,
  accessCredDisable: 33,
  authenticationStatus: 34
};

export default propertyState;