const propertyState = {
  boolean_value: 0,
  binary_value: 1,
  event_type: 2,
  polarity: 3,
  program_change: 4,
  program_state: 5,
  reason_for_halt: 6,
  reliability: 7,
  event_state: 8,
  system_status: 9,
  units: 10,
  unsigned_value: 11,
  life_safety_mode: 12,
  life_safety_state: 13,
  restart_reason: 14,
  door_alarm_state: 15,
  action: 16,
  door_secured_status: 17,
  door_status: 18,
  door_value: 19,
  file_access_method: 20,
  lock_status: 21,
  life_safety_operation: 22,
  maintenance: 23,
  node_type: 24,
  notify_type: 25,
  security_level: 26,
  shed_state: 27,
  silenced_state: 28,
  access_event: 30,
  zone_occupancy_state: 31,
  access_cred_disable_reason: 32,
  access_cred_disable: 33,
  authentication_status: 34
};

export default propertyState;